[workspace]
resolver = "2"

members = [
    "app", "wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"


[workspace.dependencies]
gstd = "=1.9.2"
sails-rs = "=0.9.2"     
sails-client-gen = "=0.9.2"
sails-idl-gen = "=0.9.2"